app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('Portal', 'AdminController@index');
Route::get('/', 'LogController@index');
Route::get('/logout', 'LogController@index');
Route::Resource('login', 'LogController');
Route::get('Calendar', 'AppointmentController@calendar');
Route::post('/uploadfile', 'FileController@uploadfile');
Route::get('/downloadfile', 'FileController@downloadfile');
Route::get('/Products/upload', 'ProductController@upload');
Route::get('/Clients/createwoh', 'ClientController@createwoh');
Route::get('/Reports/facturas', 'ReportController@factura');
Route::post('/Clients/quickstore', ['as' => 'Clients.quickstore', 'uses' =>  'ClientController@quickstore']);
Route::Resource('Users', 'UserController');
Route::Resource('Products', 'ProductController');
Route::Resource('Labs', 'LabController');
Route::Resource('Orders', 'OrderController');
Route::Resource('Orderproducts', 'OrderproductController');
Route::Resource('Payments', 'PaymentController');
Route::Resource('Clients', 'ClientController');
Route::Resource('Appointments', 'AppointmentController');
Route::Resource('Invoices', 'InvoiceController');
Route::Resource('Quicksale', 'QuicksaleController');
Route::Resource('Purchases', 'PurchaseController');
Route::Resource('Settlements', 'SettlementController');
Route::get('/JsonCliente', 'ClientController@jsonCliente');
Route::get('/JsonMedicalHistory', 'MedicalhistoryController@jsonMedicalHistory');
Route::get('/Medicalhistory', 'MedicalhistoryController@Medicalhistory');
Route::get('/JsonMedicalHistoryDate', 'MedicalhistoryController@jsonMedicalHistoryDate');
Route::get('/Factura/abono', ['as' => 'Factura.abono', 'uses' =>  'FacturaController@abono']);
Route::get('/Factura/facturaventa', ['as' => 'Factura.facturaventa', 'uses' => 'FacturaController@facturaventa']);
Route::get('/Factura/facturaventaold', ['as' => 'Factura.facturaventaold', 'uses' => 'FacturaController@facturaventaold']);
Route::get('/Factura/historiaclinica', ['as' => 'Factura.historiaclinica', 'uses' =>  'FacturaController@historiaclinica']);
Route::get('/Factura/lentes', ['as' => 'Factura.lentes', 'uses' =>  'FacturaController@lentes']);
Route::get('/Factura/pedirlentes', ['as' => 'Factura.pedirlentes', 'uses' =>  'FacturaController@pedirlentes']);
Route::get('/Factura/recomendaciones', ['as' => 'Factura.recomendaciones', 'uses' =>  'FacturaController@recomendaciones']);
Route::get('JsonProduct', 'ProductController@jsonProduct');
Route::get('JsonTypelen', 'OrderController@jsonTypelen');
Route::get('JsonFilterlenLab', 'OrderController@jsonFilterlenLab');
Route::get('JsonFilterlenId', 'OrderController@jsonFilterlenId');
Route::get('JsonMateriallen', 'OrderController@jsonMateriallen');
Route::get('JsonMaterialPrice', 'OrderController@jsonMaterialPrice');
Route::get('JsonMarklen', 'OrderController@jsonMarklen');
Route::get('JsonOrderIdentification', 'OrderController@jsonOrderIdentification');
Route::get('JsonOrderName', 'OrderController@jsonOrderName');
Route::get('JsonOrderNumber', 'OrderController@jsonOrderNumber');
Route::get('JsonOrderDate', 'OrderController@jsonOrderDate');
Route::get('JsonFacturaIdentification', 'ReportController@jsonFacturaIdentification');
Route::get('JsonFacturaName', 'ReportController@jsonFacturaName');
Route::get('JsonFacturaNumber', 'ReportController@jsonFacturaNumber');
Route::get('JsonFacturaDate', 'ReportController@jsonFacturaDate');
Route::get('JsonMarklen', 'OrderController@jsonMarklen');
Route::get('pdf', 'AdminController@pdf');
Route::post('Mailmassive', ['as' => 'Mailmassive', 'uses' => 'EmailController@mailmassive']);
Route::get('Contactmassive', 'EmailController@contactmassive');
Route::post('Mailsingle', ['as' => 'Mailsingle', 'uses' => 'EmailController@mailsingle']);
Route::get('Contactsingle', 'EmailController@contactsingle');

app/Lab.php
<?php

namespace Optitec;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Lab extends Model
{
    use SoftDeletes;

    protected $table = 'labs';
	protected $fillable = ['name', 'address', 'phone', 'contactName', 'contactPhone'];
    protected $dates = ['deleted_at'];

	public function filterlens()
    {
        return $this->hasMany('Optitec\Filterlen');
    }

    public function typelens()
    {
        return $this->hasMany('Optitec\Typelen');
    }

    protected static function boot()
    {
        parent::boot();

        static::deleting(function($lab)
        {
            $lab->typelens->each(
                function($typelens)
                {
                    $typelens->delete();
                }); 
            $lab->filterlens()->delete();
        });
    }

}

app/Http/Controllers/LabController.php
<?php

namespace Optitec\Http\Controllers;

use Illuminate\Http\Request;
use Optitec\Http\Requests;
use Optitec\Http\Controllers\Controller;
use Optitec\Http\Requests\LabRequest;
use Optitec\Lab;
use Optitec\Marklen;
use Optitec\Typelen;
use Optitec\Materiallen;
use Optitec\Filterlen;
use Optitec\materialmarkprice;
use Validator;
use Response;
use Session;
use Redirect;
use DB;

class LabController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('superuser', ['only' => []]);
        $this->middleware('administrador', ['only' => []]);
        $this->middleware('medico', ['only' => ['create', 'store', 'edit', 'update', 'destroy', 'show']]);
        $this->middleware('asesor', ['only' => ['create', 'store', 'edit', 'update', 'destroy', 'show']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $labs = Lab::paginate(15);
        return view('Lab.index', compact('labs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('Lab.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'address' => 'required',
            'phone' => 'required',
            'contactName' => 'required',
            'contactPhone' => 'required',
        ]);
        $arr = array(
            'name' => $request->name,
            'address' => $request->address,
            'phone' => $request->phone,
            'contactName' => $request->contactName,
            'contactPhone' => $request->contactPhone
            );

        if ($validator->fails()) 
        {
            return redirect('Labs/create')
                        ->withErrors($validator)
                        ->withInput($arr);
        }
        $Lab = Lab::create($request->all());
        $lab_id = $Lab->id;
        $tipos = count($request->nametypelens);
        $filtros = count($request->filter);
        for ($i=0; $i < $tipos; $i++) 
        {
            $Tipo=
            [
                'name'=>$request->nametypelens[$i],
                'lab_id'=>$lab_id,
            ];
            $Typelen = Typelen::create($Tipo);
            $type_id = $Typelen->id;
            $materiales = $request->material[$i];
            $precios = $request->precio[$i];
            $arrayIDsMateriales = [];

            for ($k=0; $k < count($materiales); $k++)
            { 
                $material = 
                [
                    'name'=>$materiales[$k],
                    'typelen_id'=>$type_id,
                    'lab_id' => $lab_id,
                    'price'=>$precios[$k],
                ];
                $Material = Materiallen::create($material);
            }      
        }

        for ($j=0; $j <$filtros ; $j++)
        { 
            $filter =
            [
                'name' => $request->filter[$j],
                'lab_id' => $lab_id,
                'price' =>$request->price[$j],
            ];                  
            Filterlen::create($filter);
        }
        return Redirect::to('/Labs');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {  
        $Lab = Lab::find($id);
        $tipos = DB::select( DB::raw("SELECT typelens.id AS IDTYPE, typelens.name AS NAMETYPE
            FROM labs
            JOIN typelens
            ON labs.id = typelens.lab_id
            WHERE labs.id = $id and typelens.deleted_at is NULL"));
        $materiales = DB::select( DB::raw("SELECT typelens.id AS IDTYPE, typelens.name AS NAMETYPE,  materiallens.id AS IDMATERIAL, materiallens.name AS NAMEMATERIAL, materiallens.price AS PRICEMATERIAL
            FROM labs
            JOIN typelens
            ON labs.id = typelens.lab_id
            JOIN materiallens
            ON typelens.id = materiallens.typelen_id
            WHERE labs.id = $id and materiallens.deleted_at is NULL"));
        $filtros = FilterLen::where('lab_id','=',$id)->orderBy('id')->get();
        return view('Lab.edit', ['lab'=>$Lab], compact('tipos', 'materiales','precios', 'filtros'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Lab = Lab::find($id);
        $Lab->fill($request->all());
        $Lab->save();
        Typelen::where('lab_id', $id)->delete();
        Filterlen::where('lab_id', $id)->delete();
        $tipos = count($request->nametypelens);
        $filtros = count($request->filter);
        for ($i=0; $i < $tipos; $i++) 
        {
            $Tipo=
            [
                'name'=>$request->nametypelens[$i],
                'lab_id'=>$id,
            ];
            $Typelen = Typelen::create($Tipo);
            $type_id = $Typelen->id;
            $materiales = $request->material[$i];
            $precios = $request->precio[$i];
            $arrayIDsMateriales = [];

            for ($k=0; $k < count($materiales); $k++)
            { 
                $material = 
                [
                    'name'=>$materiales[$k],
                    'typelen_id'=>$type_id,
                    'lab_id' => $id,
                    'price'=>$precios[$k],
                ];
                $Material = Materiallen::create($material);
            }      
        }

        for ($j=0; $j <$filtros ; $j++)
        { 
            $filter =
            [
                'name' => $request->filter[$j],
                'lab_id' => $id,
                'price' =>$request->price[$j],
            ];                  
            Filterlen::create($filter);
        }
        Session::flash('message', 'laboratorio modificado correctamente');
        return Redirect::to('/Labs');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        Lab::destroy($id);
        Session::flash('message', 'laboratorio eliminado correctamente');
        return Redirect::to('/Labs'); 
    }
}

resources/views/Lab/create.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.AlertsRequest')
		@include('alerts.SuccessRequest')
		@include('alerts.ErrorsRequest')
		<div class="">
		  <div class="page-title">
		    <div class="title_left">
		      <h3>Laboratorios</h3>
		    </div>
		  </div>
		  <div class="clearfix"></div>
		  <div class="row">
		    <div class="col-md-12 col-sm-12 col-xs-12">
		      <div class="x_panel">
		        <div class="x_title">
		          <h2>Crear laboratorio <small>Plantilla de creación de laboratorios</small></h2>
		          <div class="clearfix"></div>
		        </div>
		        <div class="x_content">
		        	<br />
		        	{!!Form::open(['route'=>'Labs.store', 'method'=>'POST', 'autocomplete'=>'off', 'class'=>'form-horizontal form-label-left', 'id'=>'demo-form2'])!!}
						@include('Forms.Labs')
						<div class="form-group">
						  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3"> 
						    {!!Form::submit('Crear',['id'=>'crear', 'class'=>'btn btn-primary'])!!}
						  </div>
						</div>
					{!!Form::close()!!}
				</div>
		      </div>
		    </div>
		  </div>  
		</div>
	@stop	

resources/views/Lab/edit.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.AlertsRequest')
		@include('alerts.SuccessRequest')
		@include('alerts.ErrorsRequest')
		<div class="">
		  <div class="page-title">
		    <div class="title_left">
		      <h3>Laboratorios</h3>
		    </div>
		  </div>
		  <div class="clearfix"></div>
		  <div class="row">
		    <div class="col-md-12 col-sm-12 col-xs-12">
		      <div class="x_panel">
		        <div class="x_title">
		          <h2>Editar laboratorio <small>Plantilla de edición de laboratorio</small></h2>
		          <div class="clearfix"></div>
		        </div>
		        <div class="x_content">
		        <br />
				{!!Form::model($lab, ['route'=>['Labs.update',$lab->id],  'method'=>'PUT', 'autocomplete'=>'off', 'class'=>'form-horizontal form-label-left', 'id'=>'demo-form2'])!!}
					@include('Forms.LabsMod')
					<div class="form-group">
						<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							{!!Form::submit('Actualizar',['class'=>'btn btn-primary'])!!}
						</div>
					</div>
				{!!Form::close()!!}
				<br>
				{!!Form::open(['route'=>['Labs.destroy', $lab->id], 'method'=>'DELETE'])!!}
					<div class="form-group">
						<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
						{!!Form::submit('Eliminar',['id'=>'eliminar', 'class'=>'btn btn-danger'])!!}
						</div>
					</div>
				{!!Form::close()!!}
				</div>
		      </div>
		    </div>
		  </div>  
		</div>
	@stop
	

resources/views/Lab/index.blade.php
@extends('layouts.admin')
@section('content')	
@include('alerts.AlertsRequest')
@include('alerts.SuccessRequest')
@include('alerts.ErrorsRequest')
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Listado de laboratorios </h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
					</li>
    			</ul>
    			<div class="clearfix"></div>
      		</div>
    		<div class="x_content">
			<table id="datatable" class="table table-hover">
				<thead>
					<th>Nombre</th>
					<th>Dirección</th>
					<th>Teléfono</th>
					<th>Nombre de contacto</th>
					<th>Teléfono de contacto</th>
					<th>Operación</th>
				</thead>
				@foreach($labs as $lab)				
				<tbody>
					<td>{{$lab->name}}</td>
					<td>{{$lab->address}}</td>
					<td>{{$lab->phone}}</td>
					<td>{{$lab->contactName}}</td>
					<td>{{$lab->contactPhone}}</td>
					<td>
						{!!link_to_route('Labs.edit', $title = 'Editar', $parameters =$lab->id, $attributes = ['class'=>'btn btn-primary'])!!}
					</td>
				</tbody>
				@endforeach		
			</table>
			{!! $labs->render() !!}
			</div>
		</div>
	</div>
</div>
@stop