app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('Portal', 'AdminController@index');
Route::get('/', 'LogController@index');
Route::get('/logout', 'LogController@index');
Route::Resource('login', 'LogController');
Route::get('Calendar', 'AppointmentController@calendar');
Route::post('/uploadfile', 'FileController@uploadfile');
Route::get('/downloadfile', 'FileController@downloadfile');
Route::get('/Products/upload', 'ProductController@upload');
Route::get('/Clients/createwoh', 'ClientController@createwoh');
Route::get('/Reports/facturas', 'ReportController@factura');
Route::post('/Clients/quickstore', ['as' => 'Clients.quickstore', 'uses' =>  'ClientController@quickstore']);
Route::Resource('Users', 'UserController');
Route::Resource('Products', 'ProductController');
Route::Resource('Labs', 'LabController');
Route::Resource('Orders', 'OrderController');
Route::Resource('Orderproducts', 'OrderproductController');
Route::Resource('Payments', 'PaymentController');
Route::Resource('Clients', 'ClientController');
Route::Resource('Appointments', 'AppointmentController');
Route::Resource('Invoices', 'InvoiceController');
Route::Resource('Quicksale', 'QuicksaleController');
Route::Resource('Purchases', 'PurchaseController');
Route::Resource('Settlements', 'SettlementController');
Route::get('/JsonCliente', 'ClientController@jsonCliente');
Route::get('/JsonMedicalHistory', 'MedicalhistoryController@jsonMedicalHistory');
Route::get('/Medicalhistory', 'MedicalhistoryController@Medicalhistory');
Route::get('/JsonMedicalHistoryDate', 'MedicalhistoryController@jsonMedicalHistoryDate');
Route::get('/Factura/abono', ['as' => 'Factura.abono', 'uses' =>  'FacturaController@abono']);
Route::get('/Factura/facturaventa', ['as' => 'Factura.facturaventa', 'uses' => 'FacturaController@facturaventa']);
Route::get('/Factura/facturaventaold', ['as' => 'Factura.facturaventaold', 'uses' => 'FacturaController@facturaventaold']);
Route::get('/Factura/historiaclinica', ['as' => 'Factura.historiaclinica', 'uses' =>  'FacturaController@historiaclinica']);
Route::get('/Factura/lentes', ['as' => 'Factura.lentes', 'uses' =>  'FacturaController@lentes']);
Route::get('/Factura/pedirlentes', ['as' => 'Factura.pedirlentes', 'uses' =>  'FacturaController@pedirlentes']);
Route::get('/Factura/recomendaciones', ['as' => 'Factura.recomendaciones', 'uses' =>  'FacturaController@recomendaciones']);
Route::get('JsonProduct', 'ProductController@jsonProduct');
Route::get('JsonTypelen', 'OrderController@jsonTypelen');
Route::get('JsonFilterlenLab', 'OrderController@jsonFilterlenLab');
Route::get('JsonFilterlenId', 'OrderController@jsonFilterlenId');
Route::get('JsonMateriallen', 'OrderController@jsonMateriallen');
Route::get('JsonMaterialPrice', 'OrderController@jsonMaterialPrice');
Route::get('JsonMarklen', 'OrderController@jsonMarklen');
Route::get('JsonOrderIdentification', 'OrderController@jsonOrderIdentification');
Route::get('JsonOrderName', 'OrderController@jsonOrderName');
Route::get('JsonOrderNumber', 'OrderController@jsonOrderNumber');
Route::get('JsonOrderDate', 'OrderController@jsonOrderDate');
Route::get('JsonFacturaIdentification', 'ReportController@jsonFacturaIdentification');
Route::get('JsonFacturaName', 'ReportController@jsonFacturaName');
Route::get('JsonFacturaNumber', 'ReportController@jsonFacturaNumber');
Route::get('JsonFacturaDate', 'ReportController@jsonFacturaDate');
Route::get('JsonMarklen', 'OrderController@jsonMarklen');
Route::get('pdf', 'AdminController@pdf');
Route::post('Mailmassive', ['as' => 'Mailmassive', 'uses' => 'EmailController@mailmassive']);
Route::get('Contactmassive', 'EmailController@contactmassive');
Route::post('Mailsingle', ['as' => 'Mailsingle', 'uses' => 'EmailController@mailsingle']);
Route::get('Contactsingle', 'EmailController@contactsingle');

app/Product.php
<?php

namespace Optitec;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Optitec\Http\Requests\ProductRequest;

class Product extends Model
{
	use SoftDeletes;
    
    protected $table = 'products';
	protected $fillable = ['name', 'reference', 'color'];
	protected $dates = ['deleted_at'];

	public function purchaseproducts()
    {
        return $this->hasMany('Optitec\Purchaseproduct');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace Optitec\Http\Controllers;

use Illuminate\Http\Request;
use Optitec\Http\Requests\ProductRequest;
use Optitec\Http\Requests;
use Optitec\Http\Controllers\Controller;
use Optitec\Product;
use Input;
use Response;
use Session;
use Redirect;
use DB;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('superuser', ['only' => []]);
        $this->middleware('administrador', ['only' => []]);
        $this->middleware('medico', ['only' => ['create', 'store', 'edit', 'update', 'destroy', 'show']]);
        $this->middleware('asesor', ['only' => ['edit', 'update', 'destroy', 'show']]);
    }

    public function jsonProduct()
    {
        $product = Input::get('product_id');
        $products = DB::table('products')
                    ->select('products.*', 'P.PRECIOVENTA')
                    ->join(DB::raw('
                    (SELECT purchaseproducts.product_id, MAX(purchaseproducts.id), purchaseproducts.salePrice AS PRECIOVENTA FROM purchaseproducts
                    WHERE purchaseproducts.deleted_at IS NULL
                    GROUP BY purchaseproducts.product_id) P'), 
                    function($join)
                    {
                       $join->on('products.id', '=', 'P.product_id');
                    })
                    ->where('products.id', '=', $product)
                    ->groupBy('products.id')
                    ->OrderBy('products.name')->first();
        return Response::json($products);
    }

    public function upload()
    {
        return view('Product.upload');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(10);
        /*$products = DB::table('products')
                        ->leftjoin('purchaseproducts', 'products.id', '=', 'purchaseproducts.product_id')
                        ->leftjoin('orderproducts', 'products.id', '=', 'orderproducts.product_id')
                        ->where('products.id', '<>', 1)
                        ->where('orderproducts.deleted_at', '=', null)
                        ->select('products.*')
                        ->addSelect(DB::raw('COALESCE(SUM(purchaseproducts.quantity),0) AS COMPRAS'))
                        ->addSelect(DB::raw('COALESCE(COUNT(orderproducts.product_id),0) AS VENTAS'))
                        ->groupBy('products.id')
                        ->OrderBy('products.name')
                        ->paginate(10);

        $products = DB::select( DB::raw("SELECT products.*, COALESCE(SUM(purchaseproducts.quantity), 0) AS COMPRAS, COALESCE(V.VENTAS, 0) AS VENTAS
                    FROM products
                    LEFT JOIN (
                    SELECT orderproducts.*, COUNT(orderproducts.product_id) AS VENTAS FROM orderproducts
                    WHERE orderproducts.deleted_at IS NULL
                    GROUP BY orderproducts.product_id) AS V
                    ON products.id = V.product_id
                    LEFT JOIN purchaseproducts
                    ON purchaseproducts.product_id = products.id
                    WHERE products.id <> 1
                    GROUP BY products.id
                    ORDER BY products.name"));*/

        $products = DB::table('products')
                    ->select('products.*')
                    ->addSelect(DB::raw('COALESCE(SUM(purchaseproducts.quantity),0) AS COMPRAS'))
                    ->addSelect(DB::raw('COALESCE(V.VENTAS,0) AS VENTAS'))
                    ->leftjoin(DB::raw('
                    (SELECT orderproducts.product_id, COUNT(orderproducts.product_id) AS VENTAS FROM orderproducts
                    WHERE orderproducts.deleted_at IS NULL
                    GROUP BY orderproducts.product_id) V'), 
                    function($leftjoin)
                    {
                       $leftjoin->on('products.id', '=', 'V.product_id');
                    })
                    ->leftjoin('purchaseproducts', 'purchaseproducts.product_id', '=', 'products.id')
                    ->where('products.id', '<>', 1)
                    ->groupBy('products.id')
                    ->OrderBy('products.name')
                    ->paginate(10);
        return view('Product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('Product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        Product::create($request->all());
        Session::flash('message', 'producto creado correctamente');
        return Redirect('/Products');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Product = Product::find($id);
        return view('Product.edit', ['product'=>$Product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Product = Product::find($id);
        $Product->fill($request->all());
        $Product->save();
        Session::flash('message', 'producto modificado correctamente');
        return Redirect::to('/Products'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);
        Session::flash('message', 'producto eliminado correctamente');
        return Redirect::to('/Products'); 
    }
}

resources/views/Product/create.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.AlertsRequest')
		@include('alerts.SuccessRequest')
		@include('alerts.ErrorsRequest')
		<div class="">
		  <div class="page-title">
		    <div class="title_left">
		      <h3>Productos</h3>
		    </div>
		  </div>
		  <div class="clearfix"></div>
		  <div class="row">
		    <div class="col-md-12 col-sm-12 col-xs-12">
		      <div class="x_panel">
		        <div class="x_title">
		          <h2>Crear producto <small>Plantilla de creación de productos</small></h2>
		          <div class="clearfix"></div>
		        </div>
		        <div class="x_content">
		        	<br />
		        	{!!Form::open(['route'=>'Products.store', 'method'=>'POST', 'autocomplete'=>'off', 'class'=>'form-horizontal form-label-left', 'id'=>'demo-form2'])!!}
						@include('Forms.Products')
						<div class="form-group">
						  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3"> 
						    {!!Form::submit('Crear',['id'=>'crear', 'class'=>'btn btn-primary'])!!}
						  </div>
						</div>
					{!!Form::close()!!}
				</div>
		      </div>
		    </div>
		  </div>  
		</div>
	@stop	

resources/views/Product/edit.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.AlertsRequest')
		@include('alerts.SuccessRequest')
		@include('alerts.ErrorsRequest')
		<div class="">
		  <div class="page-title">
		    <div class="title_left">
		      <h3>Productos</h3>
		    </div>
		  </div>
		  <div class="clearfix"></div>
		  <div class="row">
		    <div class="col-md-12 col-sm-12 col-xs-12">
		      <div class="x_panel">
		        <div class="x_title">
		          <h2>Editar producto <small>Plantilla de edición de producto</small></h2>
		          <div class="clearfix"></div>
		        </div>
		        <div class="x_content">
		        <br />
				{!!Form::model($product, ['route'=>['Products.update',$product->id],  'method'=>'PUT', 'autocomplete'=>'off', 'class'=>'form-horizontal form-label-left', 'id'=>'demo-form2'])!!}
					@include('Forms.Products')
					<div class="form-group">
						<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							{!!Form::submit('Actualizar',['class'=>'btn btn-primary'])!!}
						</div>
					</div>
				{!!Form::close()!!}
				<br>
				{!!Form::open(['route'=>['Products.destroy', $product->id], 'method'=>'DELETE'])!!}
					<div class="form-group">
						<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
						{!!Form::submit('Eliminar',['id'=>'eliminar', 'class'=>'btn btn-danger'])!!}
						</div>
					</div>
				{!!Form::close()!!}
				</div>
		      </div>
		    </div>
		  </div>  
		</div>
	@stop
	

resources/views/Product/index.blade.php
@extends('layouts.admin')
@section('content')	
@include('alerts.AlertsRequest')
@include('alerts.SuccessRequest')
@include('alerts.ErrorsRequest')
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Listado de productos </h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
					</li>
    			</ul>
    			<div class="clearfix"></div>
      		</div>
    		<div class="x_content">
    		{!! $products->render() !!}	
			<table id="datatable" class="table table-hover">
				<thead>
					<th>Nombre</th>
					<th>Referencia</th>
					<th>Color</th>
					<th>Compras</th>
					<th>Ventas</th>
					<th>Saldo</th>
					<th>Operación</th>
				</thead>
				<tbody>
					@foreach($products as $product)
					<tr>
						<td>{{$product->name}}</td>
						<td>{{$product->reference}}</td>
						<td>{{$product->color}}</td>
						<td>{{$product->COMPRAS}}</td>
						<td>{{$product->VENTAS}}</td>
						<td>{{$product->COMPRAS - $product->VENTAS}}</td>
						<td>
							{!!link_to_route('Products.edit', $title = 'Editar', $parameters =$product->id, $attributes = ['class'=>'btn btn-primary'])!!}
						</td>
					</tr>					
					@endforeach
				</tbody>	
			</table>
			{!! $products->render() !!}	
			</div>
		</div>
	</div>
</div>
@stop

resources/views/Product/upload.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.AlertsRequest')
		@include('alerts.SuccessRequest')
		@include('alerts.ErrorsRequest')
		<div class="">
			<div class="page-title">
		    	<div class="title_left">
		      		<h3>Productos</h3>
		    	</div>
		  	</div>
		  	<div class="clearfix"></div>
		  	<div class="row">
			    <div class="col-md-12 col-sm-12 col-xs-12">
			    	<div class="x_panel">
			    		<div class="x_title">
							<h2>Crear producto <small>Plantilla de creación de productos</small></h2>
			    			<div class="clearfix"></div>
			        	</div>
			        	<div class="x_content">
			        		<br />
			        		<div class="col-md-12">
								<div class="box-header">
									<h3 class="box-title">Cargar Datos de los productos</h3>
								</div><!-- /.box-header -->
								<a class="btn btn-success" href="/downloadfile?fileName=archivoproductos.xlsx" role="button"><i class="fa fa-file-excel-o" aria-hidden="true"></i> Descargar plantilla</a>					     
					      		<form  id="uploadfiles" name="uploadfiles" method="post"  action="/uploadfile" enctype="multipart/form-data" files="true" onsubmit="return validacion()">
					      			<input type="hidden" name="_token" id="_token"  value="<?= csrf_token(); ?>">             
					    			<div class="box-body">	     
					    				<div class="form-group col-xs-12"  >
					            			<label>Agregar Archivo de Excel </label>
					            			<input name="archivo" id="archivo" type="file" class="archivo form-control" required/ accept=".xls,.xlsx"><br /><br />
					        			</div>					     
					    				<div class="box-footer">
					                    	{!!Form::submit('Cargar datos',['id'=>'crear', 'class'=>'btn btn-primary'])!!}
					      				</div>		       
					    			</div>
								</form>
							</div>
						</div>
			      	</div>
			    </div>
			</div>  
		</div>
		<script>
			function validacion()
	        {
	            $('#crear').prop('value', 'enviando...');
	            $('#crear').prop('disabled', true);
	            return(true);           
        	} 
		</script>
	@stop	