app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('Portal', 'AdminController@index');
Route::get('/', 'LogController@index');
Route::get('/logout', 'LogController@index');
Route::Resource('login', 'LogController');
Route::get('Calendar', 'AppointmentController@calendar');
Route::post('/uploadfile', 'FileController@uploadfile');
Route::get('/downloadfile', 'FileController@downloadfile');
Route::get('/Products/upload', 'ProductController@upload');
Route::get('/Clients/createwoh', 'ClientController@createwoh');
Route::get('/Reports/facturas', 'ReportController@factura');
Route::post('/Clients/quickstore', ['as' => 'Clients.quickstore', 'uses' =>  'ClientController@quickstore']);
Route::Resource('Users', 'UserController');
Route::Resource('Products', 'ProductController');
Route::Resource('Labs', 'LabController');
Route::Resource('Orders', 'OrderController');
Route::Resource('Orderproducts', 'OrderproductController');
Route::Resource('Payments', 'PaymentController');
Route::Resource('Clients', 'ClientController');
Route::Resource('Appointments', 'AppointmentController');
Route::Resource('Invoices', 'InvoiceController');
Route::Resource('Quicksale', 'QuicksaleController');
Route::Resource('Purchases', 'PurchaseController');
Route::Resource('Settlements', 'SettlementController');
Route::get('/JsonCliente', 'ClientController@jsonCliente');
Route::get('/JsonMedicalHistory', 'MedicalhistoryController@jsonMedicalHistory');
Route::get('/Medicalhistory', 'MedicalhistoryController@Medicalhistory');
Route::get('/JsonMedicalHistoryDate', 'MedicalhistoryController@jsonMedicalHistoryDate');
Route::get('/Factura/abono', ['as' => 'Factura.abono', 'uses' =>  'FacturaController@abono']);
Route::get('/Factura/facturaventa', ['as' => 'Factura.facturaventa', 'uses' => 'FacturaController@facturaventa']);
Route::get('/Factura/facturaventaold', ['as' => 'Factura.facturaventaold', 'uses' => 'FacturaController@facturaventaold']);
Route::get('/Factura/historiaclinica', ['as' => 'Factura.historiaclinica', 'uses' =>  'FacturaController@historiaclinica']);
Route::get('/Factura/lentes', ['as' => 'Factura.lentes', 'uses' =>  'FacturaController@lentes']);
Route::get('/Factura/pedirlentes', ['as' => 'Factura.pedirlentes', 'uses' =>  'FacturaController@pedirlentes']);
Route::get('/Factura/recomendaciones', ['as' => 'Factura.recomendaciones', 'uses' =>  'FacturaController@recomendaciones']);
Route::get('JsonProduct', 'ProductController@jsonProduct');
Route::get('JsonTypelen', 'OrderController@jsonTypelen');
Route::get('JsonFilterlenLab', 'OrderController@jsonFilterlenLab');
Route::get('JsonFilterlenId', 'OrderController@jsonFilterlenId');
Route::get('JsonMateriallen', 'OrderController@jsonMateriallen');
Route::get('JsonMaterialPrice', 'OrderController@jsonMaterialPrice');
Route::get('JsonMarklen', 'OrderController@jsonMarklen');
Route::get('JsonOrderIdentification', 'OrderController@jsonOrderIdentification');
Route::get('JsonOrderName', 'OrderController@jsonOrderName');
Route::get('JsonOrderNumber', 'OrderController@jsonOrderNumber');
Route::get('JsonOrderDate', 'OrderController@jsonOrderDate');
Route::get('JsonFacturaIdentification', 'ReportController@jsonFacturaIdentification');
Route::get('JsonFacturaName', 'ReportController@jsonFacturaName');
Route::get('JsonFacturaNumber', 'ReportController@jsonFacturaNumber');
Route::get('JsonFacturaDate', 'ReportController@jsonFacturaDate');
Route::get('JsonMarklen', 'OrderController@jsonMarklen');
Route::get('pdf', 'AdminController@pdf');
Route::post('Mailmassive', ['as' => 'Mailmassive', 'uses' => 'EmailController@mailmassive']);
Route::get('Contactmassive', 'EmailController@contactmassive');
Route::post('Mailsingle', ['as' => 'Mailsingle', 'uses' => 'EmailController@mailsingle']);
Route::get('Contactsingle', 'EmailController@contactsingle');

app/Purchase.php
<?php

namespace Optitec;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Purchase extends Model
{
    use SoftDeletes;
    protected $table = 'purchases';
	protected $fillable = ['invoicepurchase', 'seller'];
    protected $dates = ['deleted_at'];
}

app/Http/Controllers/PurchaseController.php
<?php

namespace Optitec\Http\Controllers;

use Illuminate\Http\Request;
use Optitec\Http\Requests;
use Optitec\Http\Controllers\Controller;
use Optitec\Http\Requests\PurchaseRequest;
use Optitec\Product;
use Optitec\Purchase;
use Optitec\Purchaseproduct;
use Redirect;
use DB;
use Session;

class PurchaseController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
		$this->middleware('superuser', ['only' => []]);
        $this->middleware('administrador', ['only' => []]);
        $this->middleware('medico');
        $this->middleware('asesor', ['only' => ['edit', 'update', 'destroy', 'show']]);
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{

		$Purchases = DB::table('purchases')
						->join('purchaseproducts', 'purchases.id', '=', 'purchaseproducts.purchase_id')
						->where('purchases.deleted_at', '=', null)
						->where('purchaseproducts.deleted_at', '=', null)
						->groupBy('purchases.id')
						->select('purchases.*')
						->addSelect(DB::raw('SUM(purchaseproducts.purchasePrice * purchaseproducts.quantity) AS TOTAL'))
						->paginate(10);
		return view('Purchase.index', compact('Purchases'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$products = Product::select(DB::raw('CONCAT(name,"-",reference, "-", color)  AS NP'), 'id')->where('products.id', '<>', 1)->lists('NP', 'id');
		$purchaseproducts = Purchaseproduct::where('purchaseproducts.purchase_id', '=', -1)->get();
		return view('Purchase.create', compact('products', 'purchaseproducts'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(PurchaseRequest $request)
	{
		$Purchase = Purchase::create($request->all());
		for ($i=0; $i < count($request->product_id); $i++)
		{ 
			$purchaseproduct = 
			[
				'purchase_id'=>$Purchase->id,
				'product_id' =>$request->product_id[$i],
				'purchasePrice'=>$request->purchasePrice[$i],
				'salePrice'=>$request->salePrice[$i],
				'quantity'=>$request->quantity[$i],
			];
			purchaseproduct::create($purchaseproduct);
		}
		Session::flash('message', 'compra creada correctamente');
		return Redirect('/Purchases');   
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		$Purchase = Purchase::find($id);
		$products = Product::select(DB::raw('CONCAT(name,"-",reference, "-", color)  AS NP'), 'id')->lists('NP', 'id');
		$purchaseproducts = Purchaseproduct::where('purchaseproducts.purchase_id', '=', $id)->get();
        return view('Purchase.edit', ['purchase'=>$Purchase], compact('products', 'purchaseproducts'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$Purchase = Purchase::find($id);
        $Purchase->fill($request->all());
        $Purchase->save();


        Purchaseproduct::where('purchaseproducts.purchase_id', $id)->delete();
        for ($i=0; $i < count($request->product_id); $i++)
		{ 
			$purchaseproduct = 
			[
				'purchase_id'=>$Purchase->id,
				'product_id' =>$request->product_id[$i],
				'purchasePrice'=>$request->purchasePrice[$i],
				'salePrice'=>$request->salePrice[$i],
				'quantity'=>$request->quantity[$i],
			];
			Purchaseproduct::create($purchaseproduct);
		}


        Session::flash('message', 'compra modificada correctamente');
        return Redirect::to('/Purchases'); 
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		Purchaseproduct::where('purchaseproducts.purchase_id', $id)->delete();
		Purchase::destroy($id);
        Session::flash('message', 'compra eliminada correctamente');
        return Redirect::to('/Purchases'); 
	}
}

resources/views/Purchase/create.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.AlertsRequest')
		@include('alerts.SuccessRequest')
		@include('alerts.ErrorsRequest')
		<div class="">
		  <div class="page-title">
		    <div class="title_left">
		      <h3>Compras</h3>
		    </div>
		  </div>
		  <div class="clearfix"></div>
		  <div class="row">
		    <div class="col-md-12 col-sm-12 col-xs-12">
		      <div class="x_panel">
		        <div class="x_title">
		          <h2>Crear compras <small>Plantilla de creación de compras</small></h2>
		          <div class="clearfix"></div>
		        </div>
		        <div class="x_content">
		        	<br />
		        	{!!Form::open(['route'=>'Purchases.store', 'method'=>'POST', 'autocomplete'=>'off', 'class'=>'form-horizontal form-label-left', 'id'=>'demo-form2', 'onsubmit'=>'return validacion()'])!!}
						@include('Forms.Purchases')
						<div class="form-group">
						  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3"> 
						    {!!Form::submit('Crear',['id'=>'crear', 'class'=>'btn btn-primary'])!!}
						  </div>
						</div>
					{!!Form::close()!!}
				</div>
		      </div>
		    </div>
		  </div>  
		</div>
		<script type="text/javascript">
			$(document).ready(function()
			{
				$('.selectClass').select2();
			});
			function validacion()
	        {
	            $('#crear').prop('value', 'enviando...');
	            $('#crear').prop('disabled', true);
	            return(true);           
	        }    
		</script>
	@stop	

resources/views/Purchase/edit.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.AlertsRequest')
		@include('alerts.SuccessRequest')
		@include('alerts.ErrorsRequest')
		<div class="">
		  <div class="page-title">
		    <div class="title_left">
		      <h3>Compras</h3>
		    </div>
		  </div>
		  <div class="clearfix"></div>
		  <div class="row">
		    <div class="col-md-12 col-sm-12 col-xs-12">
		      <div class="x_panel">
		        <div class="x_title">
		          <h2>Editar compra <small>Plantilla de edición de compras</small></h2>
		          <div class="clearfix"></div>
		        </div>
		        <div class="x_content">
				{!!Form::model($purchase, ['route'=>['Purchases.update',$purchase->id],  'method'=>'PUT', 'autocomplete'=>'off', 'class'=>'form-horizontal form-label-left', 'id'=>'demo-form2'])!!}
					@include('Forms.Purchases')
					<div class="form-group">
						<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							{!!Form::submit('Actualizar',['class'=>'btn btn-primary'])!!}
						</div>
					</div>
				{!!Form::close()!!}
				{!!Form::open(['route'=>['Purchases.destroy', $purchase->id], 'method'=>'DELETE'])!!}
					<div class="form-group">
						<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
						{!!Form::submit('Eliminar',['id'=>'eliminar', 'class'=>'btn btn-danger'])!!}
						</div>
					</div>
				{!!Form::close()!!}
				</div>
		      </div>
		    </div>
		  </div>  
		</div>
		<script type="text/javascript">
			$(document).ready(function()
			{
				$('.selectClass').select2();
			});
		</script>
	@stop

resources/views/Purchase/index.blade.php
@extends('layouts.admin')
@section('content')	
@include('alerts.AlertsRequest')
@include('alerts.SuccessRequest')
@include('alerts.ErrorsRequest')
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Listado de compras </h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
					</li>
    			</ul>
    			<div class="clearfix"></div>
      		</div>
    		<div class="x_content">
    		{!! $Purchases->render() !!}
			<table id="datatable" class="table table-hover">
				<thead>
					<th>Número de factura</th>
					<th>Vendedor</th>
					<th>Total</th>
					<th>Operación</th>
				</thead>
				<tbody>
					@foreach($Purchases as $purchase)
					@if($purchase->invoicepurchase == null)
						<?php continue; ?>
					@endif
					<tr>
						<td>{{$purchase->invoicepurchase}}</td>
						<td>{{$purchase->seller}}</td>
						<td>{{$purchase->TOTAL}}</td>
						<td>
							{!!link_to_route('Purchases.edit', $title = 'Editar', $parameters =$purchase->id, $attributes = ['class'=>'btn btn-primary'])!!}
						</td>						
					</tr>
				@endforeach	
				</tbody>					
			</table>
			{!! $Purchases->render() !!}
			</div>
		</div>
	</div>
</div>
@stop