app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('Portal', 'AdminController@index');
Route::get('/', 'LogController@index');
Route::get('/logout', 'LogController@index');
Route::Resource('login', 'LogController');
Route::get('Calendar', 'AppointmentController@calendar');
Route::post('/uploadfile', 'FileController@uploadfile');
Route::get('/downloadfile', 'FileController@downloadfile');
Route::get('/Products/upload', 'ProductController@upload');
Route::get('/Clients/createwoh', 'ClientController@createwoh');
Route::get('/Reports/facturas', 'ReportController@factura');
Route::post('/Clients/quickstore', ['as' => 'Clients.quickstore', 'uses' =>  'ClientController@quickstore']);
Route::Resource('Users', 'UserController');
Route::Resource('Products', 'ProductController');
Route::Resource('Labs', 'LabController');
Route::Resource('Orders', 'OrderController');
Route::Resource('Orderproducts', 'OrderproductController');
Route::Resource('Payments', 'PaymentController');
Route::Resource('Clients', 'ClientController');
Route::Resource('Appointments', 'AppointmentController');
Route::Resource('Invoices', 'InvoiceController');
Route::Resource('Quicksale', 'QuicksaleController');
Route::Resource('Purchases', 'PurchaseController');
Route::Resource('Settlements', 'SettlementController');
Route::get('/JsonCliente', 'ClientController@jsonCliente');
Route::get('/JsonMedicalHistory', 'MedicalhistoryController@jsonMedicalHistory');
Route::get('/Medicalhistory', 'MedicalhistoryController@Medicalhistory');
Route::get('/JsonMedicalHistoryDate', 'MedicalhistoryController@jsonMedicalHistoryDate');
Route::get('/Factura/abono', ['as' => 'Factura.abono', 'uses' =>  'FacturaController@abono']);
Route::get('/Factura/facturaventa', ['as' => 'Factura.facturaventa', 'uses' => 'FacturaController@facturaventa']);
Route::get('/Factura/facturaventaold', ['as' => 'Factura.facturaventaold', 'uses' => 'FacturaController@facturaventaold']);
Route::get('/Factura/historiaclinica', ['as' => 'Factura.historiaclinica', 'uses' =>  'FacturaController@historiaclinica']);
Route::get('/Factura/lentes', ['as' => 'Factura.lentes', 'uses' =>  'FacturaController@lentes']);
Route::get('/Factura/pedirlentes', ['as' => 'Factura.pedirlentes', 'uses' =>  'FacturaController@pedirlentes']);
Route::get('/Factura/recomendaciones', ['as' => 'Factura.recomendaciones', 'uses' =>  'FacturaController@recomendaciones']);
Route::get('JsonProduct', 'ProductController@jsonProduct');
Route::get('JsonTypelen', 'OrderController@jsonTypelen');
Route::get('JsonFilterlenLab', 'OrderController@jsonFilterlenLab');
Route::get('JsonFilterlenId', 'OrderController@jsonFilterlenId');
Route::get('JsonMateriallen', 'OrderController@jsonMateriallen');
Route::get('JsonMaterialPrice', 'OrderController@jsonMaterialPrice');
Route::get('JsonMarklen', 'OrderController@jsonMarklen');
Route::get('JsonOrderIdentification', 'OrderController@jsonOrderIdentification');
Route::get('JsonOrderName', 'OrderController@jsonOrderName');
Route::get('JsonOrderNumber', 'OrderController@jsonOrderNumber');
Route::get('JsonOrderDate', 'OrderController@jsonOrderDate');
Route::get('JsonFacturaIdentification', 'ReportController@jsonFacturaIdentification');
Route::get('JsonFacturaName', 'ReportController@jsonFacturaName');
Route::get('JsonFacturaNumber', 'ReportController@jsonFacturaNumber');
Route::get('JsonFacturaDate', 'ReportController@jsonFacturaDate');
Route::get('JsonMarklen', 'OrderController@jsonMarklen');
Route::get('pdf', 'AdminController@pdf');
Route::post('Mailmassive', ['as' => 'Mailmassive', 'uses' => 'EmailController@mailmassive']);
Route::get('Contactmassive', 'EmailController@contactmassive');
Route::post('Mailsingle', ['as' => 'Mailsingle', 'uses' => 'EmailController@mailsingle']);
Route::get('Contactsingle', 'EmailController@contactsingle');

app/User.php
<?php

namespace Optitec;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword, SoftDeletes;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['firstname', 'lastname', 'email', 'user', 'password', 'role_id', 'register'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    protected $dates = ['deleted_at'];

    public function setPasswordAttribute($valor)
    {
        if(!empty($valor))
        {
            $this->attributes['password'] = \Hash::make($valor);
        }
    }
    
    public function role()
    {
        return $this->belongsTo('Optitec\Role');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace Optitec\Http\Controllers;

use Illuminate\Http\Request;
use Optitec\Http\Requests\UserRequest;
use Optitec\Http\Requests;
use Optitec\Http\Controllers\Controller;
use Optitec\User;
use Optitec\Role;
use Session;
use Redirect;
use DB;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('superuser', ['only' => []]);
        $this->middleware('administrador', ['only' => []]);
        $this->middleware('medico');
        $this->middleware('asesor');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('users.role_id', '<>', '1')->paginate(15);
        return view('User.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::where('id', '<>', '1')->lists('name','id');
        return view('User.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        User::create($request->all());
        Session::flash('message', 'perfil creado correctamente');
        return Redirect('/Users');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $User = User::find($id);
        $roles = Role::lists('name','id');
        return view('User.edit', ['user'=>$User], compact('roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $User = User::find($id);
        $User->fill($request->all());
        $User->save();
        Session::flash('message', 'perfil modificado correctamente');
        return Redirect::to('/Users'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        Session::flash('message', 'perfil eliminado correctamente');
        return Redirect::to('/Users'); 
    }
}

resources/views/User/create.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.AlertsRequest')
		@include('alerts.SuccessRequest')
		@include('alerts.ErrorsRequest')
		<div class="">
		  <div class="page-title">
		    <div class="title_left">
		      <h3>Usuarios</h3>
		    </div>
		  </div>
		  <div class="clearfix"></div>
		  <div class="row">
		    <div class="col-md-12 col-sm-12 col-xs-12">
		      <div class="x_panel">
		        <div class="x_title">
		          <h2>Crear usuario <small>Plantilla de creación de usuarios</small></h2>
		          <div class="clearfix"></div>
		        </div>
		        <div class="x_content">
		        	<br />
		        	{!!Form::open(['route'=>'Users.store', 'method'=>'POST', 'autocomplete'=>'off', 'class'=>'form-horizontal form-label-left', 'id'=>'demo-form2', 'autocomplete'=>'off'])!!}
						@include('Forms.Users')
						<div class="form-group">
						  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3"> 
						    {!!Form::submit('Crear',['id'=>'crear', 'class'=>'btn btn-primary'])!!}
						  </div>
						</div>
					{!!Form::close()!!}
				</div>
		      </div>
		    </div>
		  </div>  
		</div>
	@stop	

resources/views/User/edit.blade.php
@extends('layouts.admin')
	@section('content')
		@include('alerts.AlertsRequest')
		@include('alerts.SuccessRequest')
		@include('alerts.ErrorsRequest')
		<div class="">
		  <div class="page-title">
		    <div class="title_left">
		      <h3>Usuarios</h3>
		    </div>
		  </div>
		  <div class="clearfix"></div>
		  <div class="row">
		    <div class="col-md-12 col-sm-12 col-xs-12">
		      <div class="x_panel">
		        <div class="x_title">
		          <h2>Crear usuario <small>Plantilla de creación de usuarios</small></h2>
		          <div class="clearfix"></div>
		        </div>
		        <div class="x_content">
				{!!Form::model($user, ['route'=>['Users.update',$user->id],  'method'=>'PUT', 'autocomplete'=>'off', 'class'=>'form-horizontal form-label-left', 'id'=>'demo-form2'])!!}
					@include('Forms.Users')
					<div class="form-group">
						<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
							{!!Form::submit('Actualizar',['class'=>'btn btn-primary'])!!}
						</div>
					</div>
				{!!Form::close()!!}
				{!!Form::open(['route'=>['Users.destroy', $user->id], 'method'=>'DELETE'])!!}
					<div class="form-group">
						<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
						{!!Form::submit('Eliminar',['id'=>'eliminar', 'class'=>'btn btn-danger'])!!}
						</div>
					</div>
				{!!Form::close()!!}
				</div>
		      </div>
		    </div>
		  </div>  
		</div>
	@stop
	

resources/views/User/index.blade.php
@extends('layouts.admin')
@section('content')	
@include('alerts.AlertsRequest')
@include('alerts.SuccessRequest')
@include('alerts.ErrorsRequest')
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_title">
				<h2>Listado de perfiles </h2>
				<ul class="nav navbar-right panel_toolbox">
					<li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
					</li>
    			</ul>
    			<div class="clearfix"></div>
      		</div>
    		<div class="x_content">
			<table id="datatable" class="table table-hover">
				<thead>
					<th>Rol</th>
					<th>Nombres</th>
					<th>Apellidos</th>
					<th>Correo</th>
					<th>Usuario</th>
					<th>Registro</th>
					<th>Operación</th>
				</thead>
				<tbody>
					@foreach($users as $user)
					<tr>
						<td>{{$user->role->name}}</td>
						<td>{{$user->firstname}}</td>
						<td>{{$user->lastname}}</td>
						<td>{{$user->email}}</td>
						<td>{{$user->user}}</td>
						<td>{{$user->register}}</td>
						<td>
							{!!link_to_route('Users.edit', $title = 'Editar', $parameters =$user->id, $attributes = ['class'=>'btn btn-primary'])!!}
						</td>
					</tr>					
					@endforeach	
				</tbody>	
				{!! $users->render() !!}				
			</table>
			</div>
		</div>
	</div>
</div>
@stop